### ISSUE TITLE
Closed issues are seen as created issues

### ISSUE THREAD

**Issue by mschader** [f-breidenstein/go-gitlab-irc#6] opened 2017-07-20 19:33 UTC
### Expected Behaviour
When closing an issue, the bot should output: "[...] **closed** issue #[...]"

### Actual Behaviour
The bot output is: "[...] **created** issue #[...]"

**Comment by fleaz** [comment] 2017-07-20 20:08
Duplicate of #1 :stuck_out_tongue:

**Closed as completed by fleaz** 2017-07-20 20:08 UTC
